### ISSUE TITLE
Current build order in PHP container Dockerfile results in exception

### ISSUE THREAD

**Issue by jskowronski39** [ArmaForces/Website#1]
During build operation `composer dump-env prod` step (16/40) is executed before `composer install` step (18/40) which results in error in console:
![obraz](https://user-images.githubusercontent.com/20958025/70379963-5ac3da00-1934-11ea-902b-e2338d79994e.png)

**Comment by veteran29** [comment]
Results of me trying to merge upstream updates from API Platform docker file, will be fixed ASAP.

**Comment by veteran29** [comment]
Fixed in 8ef686a140a14485ece12c55cbdfdceecd447181
