### ISSUE TITLE
User profile/logout button is invisible after avatar was changed

### ISSUE THREAD

**Issue by veteran29** [ArmaForces/Website#118]
We refresh it on every login, that is fine but we need some fallback background in case discord avatar could not be loaded correctly.

![image](https://user-images.githubusercontent.com/4293906/102145888-5a73ee00-3e68-11eb-9577-8ceff1608cc8.png)

**Comment by 3Mydlo3** [comment]
Isn't this also related to profile button being invisible when user has default avatar?
![obraz](https://user-images.githubusercontent.com/30000580/102146272-f271d780-3e68-11eb-87db-694fe64eac5e.png)

**Comment by veteran29** [comment]
Default avatars should be fetched, maybe something in discord changed how their url should be formatted.
