### ISSUE TITLE
Not all group permissions for mods and modlists work

### ISSUE THREAD

**Issue by 3Mydlo3** [ArmaForces/Website#187]
I've discovered some issues with permissions:
- ~~Permission for mod removal doesn't work neither by assigning the permission to user nor to group.~~
- Permission for changing mod status works only if assigned to user.
- Having all permissions assigned to group I wasn't able to change modlist owner. When I assigned myself all the permissions, the option to change owners appeared.

**Comment by 3Mydlo3** [comment]
Update, not all permissions for modlists work too. Having all permissions assigned to group I wasn't able to change modlist owner. When I assigned myself all the permissions, the option to change owners appeared.

**Comment by 3Mydlo3** [comment]
I also do have a question. If I'm the modlist owner, without any additional permissions, should the option to change owner appear for me or not? Because it doesn't show up and I don't remember how it was before the update.

**Comment by jskowronski39** [comment]
> Permission for mod removal doesn't work neither by assigning the permission to user nor to group.
Unfortunately I cannot recreate this issue. Mods can be successfully removed if user has delete permission granted either via group or directly.

> Permission for changing mod status works only if assigned to user.
> Having all permissions assigned to group I wasn't able to change modlist owner (...)
There was an issue with how permissions were checked. Fixed in related PR.

> I also do have a question. If I'm the modlist owner, without any additional permissions, should the option to change owner appear for me or not? Because it doesn't show up and I don't remember how it was before the update.
Option to change owner appears only if user has full update permissions.

**Comment by 3Mydlo3** [comment]
> Unfortunately I cannot recreate this issue. Mods can be successfully removed if user has delete permission granted either via group or directly.

After further investigating the issue I found out the delete option is there indeed. But I had too low window width and I needed to scroll the table to the right which I did by an accident. I didn't know it can be scrolled sideways.
