### ISSUE TITLE
Mission with closed sign ups doesn't show as upcoming anymore

### ISSUE THREAD

**Issue by 3Mydlo3** [ArmaForces/Website#50]
When sign ups are closed, missions are moved to archive. Next mission with open sign ups is showed as first upcoming mission, which is invalid. It can mislead people to think that mission was cancelled.

**Comment by veteran29** [comment]
@Ilddor any proposals how this could be improved in Bot api? Maybe 3 states for mission, Open/Closed/Archived?

**Comment by Ilddor** [comment]
Actually currently it is possible to handle it entirely by a website as date of the mission as well as closing date is provided in data returned. However additional state can be added if required.

**Comment by 3Mydlo3** [comment]
I would suggest separate state for missions and sign ups. Open/Closed/Archived as one attribute for both missions and sign ups just doesn't feel right.

Missions could be `scheduled`, `finished` and `cancelled`, sign ups `opened`, `closed` and maybe also `scheduled` which is not something unrealistic.

**Comment by jskowronski39** [comment]
@veteran29 Can we implement temporary solution for this issue based on date? Would it be possible regarding time settings inside container and timezone in php.ini?
